name       : shotcut
version    : '18.03'
release    : 8
source     :
    - https://github.com/mltframework/shotcut/archive/v18.03.tar.gz : d1bbd9df4a58c084ac059f56b02737ead5e37c197fabaedc965260c377a0f6ab
license    : GPL-3.0
component  : multimedia.video
summary    : Shotcut - a free, open source, cross-platform video editor
description: |
    Shotcut - a free, open source, cross-platform video editor
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(mlt++)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
rundeps    :
    - jack-audio-connection-kit
    - qt5-graphicaleffects
    - qt5-quickcontrols
    - sdl2
    - swh-plugins
    - webvfx
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-path-for-nice.patch
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 icons/shotcut-logo-64.png $installdir/usr/share/icons/hicolor/64x64/apps/shotcut.png
    install -D -m 00644 $pkgfiles/shotcut.desktop $installdir/usr/share/applications/shotcut.desktop
