name       : shotcut
version    : 20.09.13
release    : 21
source     :
    - https://github.com/mltframework/shotcut/archive/v20.09.13.tar.gz : 003cb4e030b5b865d7860e909355d272e75102413f2fb81b8ea62a5ec87f6c4b
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : Shotcut - a free, open source, cross-platform video editor
description: |
    Shotcut - a free, open source, cross-platform video editor
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(mlt++)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
rundeps    :
    - jack-audio-connection-kit
    - qt5-graphicaleffects
    - qt5-quickcontrols
    - sdl2
    - swh-plugins
    - webvfx
setup      : |
    %qmake PREFIX=$installdir/usr SHOTCUT_VERSION=%version%
build      : |
    %make
install    : |
    %make_install
    %qml_cache
