name       : shotcut
version    : '17.04'
release    : 5
source     :
    - https://github.com/mltframework/shotcut/archive/v17.04.tar.gz : cddb0dee2e30803fdbb5c7372dd8126bf54b52634f166078d7c21d49d9cd40c4
license    : GPL-3.0
component  : multimedia.video
summary    : Shotcut - a free, open source, cross-platform video editor
description: |
    Shotcut - a free, open source, cross-platform video editor
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(mlt++)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
rundeps    :
    - qt5-quickcontrols
setup      : |
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 icons/shotcut-logo-64.png $installdir/usr/share/icons/hicolor/64x64/apps/shotcut.png
    install -D -m 00644 $pkgfiles/shotcut.desktop $installdir/usr/share/applications/shotcut.desktop
