name       : shotcut
version    : 21.02.27
release    : 27
source     :
    - https://github.com/mltframework/shotcut/archive/v21.02.27.tar.gz : 5ca5a5fb4b13a9da72a1bcff665af5c55fff2516bc90850d128c282d1f4296e9
license    : GPL-3.0-or-later
component  : multimedia.video
homepage   : https://www.shotcut.org/
summary    : Shotcut - a free, open source, cross-platform video editor
description: |
    Shotcut - a free, open source, cross-platform video editor
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(mlt++)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
rundeps    :
    - frei0r
    - sdl2
    - swh-plugins
setup      : |
    %qmake PREFIX=$installdir/usr SHOTCUT_VERSION=%version%
build      : |
    %make
install    : |
    %make_install
    %qml_cache
