name       : shotcut
version    : '16.11'
release    : 3
source     :
    - https://github.com/mltframework/shotcut/archive/v16.11.tar.gz : b801e36b04db2cb06156bd922510a4bdc145de27898b1bfdc37b1e5ce6e202f0
license    : GPL-3.0
component  : multimedia.video
summary    : Shotcut - a free, open source, cross-platform video editor
description: |
    Shotcut - a free, open source, cross-platform video editor
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(mlt++)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
rundeps    :
    - qt5-quickcontrols
setup      : |
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 icons/shotcut-logo-64.png $installdir/usr/share/icons/hicolor/64x64/apps/shotcut.png
    install -D -m 00644 $pkgfiles/shotcut.desktop $installdir/usr/share/applications/shotcut.desktop
