name       : shotcut
version    : 21.09.20
release    : 32
source     :
    - https://github.com/mltframework/shotcut/archive/refs/tags/v21.09.20.tar.gz : f95f1aa5a7360b68ce9f2b1cffdb7344ff3db086bad77068233eb83114f25790
license    : GPL-3.0-or-later
component  : multimedia.video
homepage   : https://www.shotcut.org/
summary    : A free, open source, and cross-platform video editor
description: |
    Shotcut is a free and open-source cross-platform video editing application for FreeBSD, Linux, macOS and Windows. It supports video, audio, and image formats via FFmpeg, and uses a timeline for non-linear video editing of multiple tracks that may be composed of various file formats. Scrubbing and transport control are assisted by OpenGL GPU-based processing and a number of video and audio filters are available.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(mlt-framework-7)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
rundeps    :
    - frei0r
    - sdl2
    - swh-plugins
    - qt5-quickcontrols
setup      : |
    %qmake \
        PREFIX=$installdir/usr \
        SHOTCUT_VERSION=%version% \
        DEFINES+=SHOTCUT_NOUPGRADE
build      : |
    %make
install    : |
    %make_install
    %qml_cache
