name       : shotcut
version    : 19.09.14
release    : 13
source     :
    - https://github.com/mltframework/shotcut/archive/v19.09.14.tar.gz : b8e2dfa95928a8b08d4427a379a56efea79301ba82aee63f0f2f883a8269eb51
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : Shotcut - a free, open source, cross-platform video editor
description: |
    Shotcut - a free, open source, cross-platform video editor
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(mlt++)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
rundeps    :
    - jack-audio-connection-kit
    - qt5-graphicaleffects
    - qt5-quickcontrols
    - sdl2
    - swh-plugins
    - webvfx
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-path-for-nice.patch
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
    %qml_cache
