name       : shotcut
version    : 19.07.15
release    : 11
source     :
    - https://github.com/mltframework/shotcut/archive/v19.07.15.tar.gz : 1e7b9dd21c3ba55a80fb4fe44367b295cde19468d392488b4a3d0fbe9a534c4c
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : Shotcut - a free, open source, cross-platform video editor
description: |
    Shotcut - a free, open source, cross-platform video editor
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(mlt++)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
rundeps    :
    - jack-audio-connection-kit
    - qt5-graphicaleffects
    - qt5-quickcontrols
    - sdl2
    - swh-plugins
    - webvfx
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-path-for-nice.patch
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
    %qml_cache
