name       : shotcut
version    : '17.05'
release    : 7
source     :
    - https://github.com/mltframework/shotcut/archive/v17.05.tar.gz : c9a2a651e5f5115684c07318bbc4f52a74eed57f44f235b484548cba7ae3fd87
license    : GPL-3.0
component  : multimedia.video
summary    : Shotcut - a free, open source, cross-platform video editor
description: |
    Shotcut - a free, open source, cross-platform video editor
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(mlt++)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
rundeps    :
    - qt5-graphicaleffects
    - qt5-quickcontrols
    - swh-plugins
    - webvfx
setup      : |
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 icons/shotcut-logo-64.png $installdir/usr/share/icons/hicolor/64x64/apps/shotcut.png
    install -D -m 00644 $pkgfiles/shotcut.desktop $installdir/usr/share/applications/shotcut.desktop
