name       : shotcut
version    : 21.01.29
release    : 25
source     :
    - https://github.com/mltframework/shotcut/archive/v21.01.29.tar.gz : 2e55e36d95344758f220b081b1f25f90eb3d0131b0a4af9d65871798079ee961
license    : GPL-3.0-or-later
component  : multimedia.video
homepage   : https://www.shotcut.org/
summary    : Shotcut - a free, open source, cross-platform video editor
description: |
    Shotcut - a free, open source, cross-platform video editor
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(mlt++)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
rundeps    :
    - frei0r
    - sdl2
    - swh-plugins
setup      : |
    %qmake PREFIX=$installdir/usr SHOTCUT_VERSION=%version%
build      : |
    %make
install    : |
    %make_install
    %qml_cache
