name       : shotcut
version    : 16.09
release    : 1
source     :
    - https://github.com/mltframework/shotcut/archive/v16.09.tar.gz : d561aa8a0bcd19272900a47405ec8d2d88bb341008c5ca0205b3b0223da66d92
license    : GPL-3.0
component  : multimedia.video
summary    : Shotcut - a free, open source, cross-platform video editor
description: |
    Shotcut - a free, open source, cross-platform video editor
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(mlt++)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
setup      : |
    qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 icons/shotcut-logo-64.png $installdir/usr/share/icons/hicolor/64x64/apps/shotcut.png
    install -D -m 00644 $pkgfiles/shotcut.desktop $installdir/usr/share/applications/shotcut.desktop
