name       : shotcut
version    : 18.10.08
release    : 9
source     :
    - https://github.com/mltframework/shotcut/archive/v18.10.08.tar.gz : 0883cbab0d5ae239a40720961cea66e5fe2a181e33b46b7ed1654229c30f8166
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : Shotcut - a free, open source, cross-platform video editor
description: |
    Shotcut - a free, open source, cross-platform video editor
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(mlt++)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
rundeps    :
    - jack-audio-connection-kit
    - qt5-graphicaleffects
    - qt5-quickcontrols
    - sdl2
    - swh-plugins
    - webvfx
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-path-for-nice.patch
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 icons/shotcut-logo-64.png $installdir/usr/share/icons/hicolor/64x64/apps/shotcut.png
    install -Dm00644 $pkgfiles/shotcut.desktop $installdir/usr/share/applications/shotcut.desktop

    %qml_cache
