name       : shotcut
version    : 20.07.11
release    : 19
source     :
    - https://github.com/mltframework/shotcut/archive/v20.07.11.tar.gz : 775ee9dcf8879fae668659632b82825ed9a158be6a8228c4d3ef44c35099fda5
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : Shotcut - a free, open source, cross-platform video editor
description: |
    Shotcut - a free, open source, cross-platform video editor
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(mlt++)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
rundeps    :
    - jack-audio-connection-kit
    - qt5-graphicaleffects
    - qt5-quickcontrols
    - sdl2
    - swh-plugins
    - webvfx
setup      : |
    %qmake PREFIX=$installdir/usr SHOTCUT_VERSION=%version%
build      : |
    %make
install    : |
    %make_install
    %qml_cache
